# Configure the remote_theme plugin with the gh-pages branch
# or the specific tag
remote_theme: aksakalli/jekyll-doc-theme@gh-pages   

# Site settings
title: JADES
email: junjie.chu@cispa.de
description: >
  Website for "JADES: A Universal Framework for Jailbreak Assessment via Decompositional Scoring."
lang: en-US

baseurl: "/jades.github.io/" # the subpath of your site, e.g. /blog/
url: https://trustairlab.github.io/jades.github.io/ # the base hostname & protocol for your site
git_address: https://github.com/TrustAIRLab/jades.github.io
git_edit_address: https://github.com/TrustAIRLab/jades.github.io/blob/gh-pages

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: paper # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
